/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmsimulator;

/**
 *
 * @author enggv
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;


public class signup3 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form signup3
     */
    String form_no;
    
    public signup3(String formno) {
        initComponents();
        form_no = formno;
        
        l12.setText(form_no);
        getContentPane().setBackground(Color.WHITE);
        
        setVisible(true);
        
        b1.addActionListener(this);
        b2.addActionListener(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setText("Additional Details");
        l1.setToolTipText("");

        l2.setText("Account Type");

        bg1.add(r1);
        r1.setText("Saving Account");

        bg1.add(r2);
        r2.setText("Fixed Deposit Account");

        bg1.add(r3);
        r3.setText("Current Account");

        bg1.add(r4);
        r4.setText("Recurring Deposit Account");

        l3.setText("Card Number");

        l4.setText("XXXX-XXXX-XXXX-4184");

        l5.setText("(Your 16-digit Card number)");
        l5.setPreferredSize(new java.awt.Dimension(137, 10));

        l6.setText("(It would appear on ATM Card/Cheque Book and Statements)");
        l6.setPreferredSize(new java.awt.Dimension(297, 10));

        l7.setText("PIN");

        l8.setText("XXXX");

        l9.setText("(4-digit password)");
        l9.setPreferredSize(new java.awt.Dimension(89, 10));

        l10.setText("Services Required:");
        l10.setToolTipText("");

        cb1.setText("ATM Card");

        cb2.setText("Internet Banking");

        cb3.setText("Mobile Banking");

        cb4.setText("EMAIL Alerts");

        cb5.setText("Cheque Book");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb6.setText("E-Statement");
        cb6.setToolTipText("");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("I hereby declares that the above entered details correct to the best of my knowledge.");

        b1.setText("Cancel");

        b2.setText("Submit");

        l11.setText("Form No.");
        l11.setToolTipText("");

        l12.setText("Form No.");
        l12.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r1)
                                    .addComponent(r3)
                                    .addComponent(l3)
                                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l7))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l8)
                                    .addComponent(l4)
                                    .addComponent(r4)
                                    .addComponent(r2)
                                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb2)
                                    .addComponent(cb4)
                                    .addComponent(cb6)))
                            .addComponent(l10)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b2)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(l11)
                    .addComponent(l12))
                .addGap(18, 18, 18)
                .addComponent(l2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r3)
                    .addComponent(r4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(l4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(l8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1)
                    .addComponent(cb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb3)
                    .addComponent(cb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb5)
                    .addComponent(cb6))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb6ActionPerformed
    
    public void actionPerformed(ActionEvent ae){
        
        String type = null;
        if(r1.isSelected()){ 
            type = "Saving Account";
        }
        else if(r2.isSelected()){ 
            type = "Fixed Deposit Account";
        }
        else if(r3.isSelected()){ 
            type = "Current Account";
        }else if(r4.isSelected()){ 
            type = "Recurring Deposit Account";
        }
        
        long smallest = 1000000000000000L;
        long biggest =  9999999999999999L;

    // return a long between smallest and biggest (+1 to include biggest as well with the upper bound)
        long random = ThreadLocalRandom.current().nextLong(smallest, biggest+1);
        String cardno = ""+random;
        
        int pinsmallest = 1000;
        int pinbiggest = 9999;
        
        int ran = ThreadLocalRandom.current().nextInt(pinsmallest, pinbiggest+1);
        String pin = ""+ran;
        
        String facility = "";
        if(cb1.isSelected()){ 
            facility = facility + "ATM Card ";
        }
        if(cb2.isSelected()){ 
            facility = facility + "Internet Banking ";
        }
        if(cb3.isSelected()){ 
            facility = facility + "Mobile Banking ";
        }
        if(cb4.isSelected()){ 
            facility = facility + "EMAIL Alerts ";
        }
        if(cb5.isSelected()){ 
            facility = facility + "Cheque Book ";
        }
        if(cb6.isSelected()){ 
            facility = facility + "E-Statement ";
        }
        
        try{
            if(ae.getSource()==b2){
                
                if(type.equals("")){
                    JOptionPane.showMessageDialog(null, "Fill all the required fields");
                }else{
                    conn c1 = new conn();
                    String q1 = "insert into signup3 values('"+form_no+"','"+type+"','"+cardno+"','"+pin+"','"+facility+"');";  
                    String q2 = "insert into login values('"+form_no+"','"+cardno+"','"+pin+"');";
                    c1.s.executeUpdate(q1);
                    c1.s.executeUpdate(q2);
                    JOptionPane.showMessageDialog(null, "Card Number: " + cardno + "\n Pin:"+ pin);
                    
                    new deposit(pin).setVisible(true);
                    setVisible(false);
                }
            
            }else if(ae.getSource()==b1){
                System.exit(0);
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup3("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton b1;
    javax.swing.JButton b2;
    javax.swing.ButtonGroup bg1;
    javax.swing.JCheckBox cb1;
    javax.swing.JCheckBox cb2;
    javax.swing.JCheckBox cb3;
    javax.swing.JCheckBox cb4;
    javax.swing.JCheckBox cb5;
    javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox jCheckBox1;
    javax.swing.JLabel l1;
    javax.swing.JLabel l10;
    javax.swing.JLabel l11;
    javax.swing.JLabel l12;
    javax.swing.JLabel l2;
    javax.swing.JLabel l3;
    javax.swing.JLabel l4;
    javax.swing.JLabel l5;
    javax.swing.JLabel l6;
    javax.swing.JLabel l7;
    javax.swing.JLabel l8;
    javax.swing.JLabel l9;
    javax.swing.JRadioButton r1;
    javax.swing.JRadioButton r2;
    javax.swing.JRadioButton r3;
    javax.swing.JRadioButton r4;
    // End of variables declaration//GEN-END:variables
}
